# Generated by Django 4.2.3 on 2023-07-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('check_interval', models.SmallIntegerField(choices=[(30, '30 seconds'), (60, '1 minute'), (300, '5 minutes'), (600, '10 minutes')], default=60)),
                ('check_timeout', models.SmallIntegerField(default=60)),
                ('tries_to_check', models.SmallIntegerField(default=3)),
                ('is_ssl_check', models.BooleanField(default=True)),
                ('is_domain_check', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('PROGRESS', 'PROGRESS')], default='PROGRESS', max_length=10)),
                ('up_statuses', models.JSONField(default=[200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 306, 307, 308])),
                ('down_statuses', models.JSONField(default=[400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511, 520, 521, 522, 523, 524, 525, 526, 527, 530, 598, 599])),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.JSONField(default=[])),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
