# Generated by Django 4.2.3 on 2023-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteendpoint',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
