# Generated by Django 4.2.3 on 2023-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0003_alter_websiteendpoint_down_statuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteendpoint',
            name='down_statuses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='websiteendpoint',
            name='up_statuses',
            field=models.JSONField(default=list),
        ),
    ]
